### ISSUE TITLE
Не запускается скрипт

### ISSUE THREAD

**Issue by Radzhab** [mitshel/sopds#10]
Делаю по http://www.sopds.ru/index.php/forum/instruktsii-po-ustanovke/7-ustanovka-v-ubuntu-server-12-04-lts мануалу. Все настроил. Но при переходе на сайт http://веб-сервер/opds пишет **The requested URL /opds was not found on this server.** Думаю проблема в апаче. 
![GitHub Logo](http://dl2.joxi.net/drive/0004/2720/281248/150615/784349c6b1.jpg)
![GitHub Logo](http://dl2.joxi.net/drive/0004/2720/281248/150615/1ce0ae362d.jpg)

**Comment by mitshel** [comment]
вместо Apache используйте встроенный сервер
запускается так ./sopdsd.py start
после чего можно получить доступ по URL http://Бваш сервер>:8081/

**Comment by Radzhab** [comment]
Спасибо) блин что апач, что nginx. ППц одним словом. Кстати. Логин пасс где устанавливать?

**Comment by Radzhab** [comment]
Нашел сенкс)
