### ISSUE TITLE
pdf cover image

### ISSUE THREAD

**Issue by Radzhab** [mitshel/sopds#11]
Начинаю тихонько вникать в суть дела. Обложка pdf файла хранится в метафайле документа. Я не нашел метода записать картинку в pdf в виде обложки и пошел по другому пути. Думал вручную записать данные в cover и cover_type в базе. В каком виде там хранятся данные? Я пробовал url забить. Но по ходу это не то

**Comment by mitshel** [comment]
sopds пока извлекает метаинформацию только из fb2 - самом популярном формате электронных книг в России. Обложки из fb2 извлекаются на лету, поэтому в базе не хранятся.
Хранение обложек в БД не предусмотрено.
