### ISSUE TITLE
incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by aikudinov** [mitshel/sopds#13]
Словил ошибку:
AH01215: mysql.connector.errors.ProgrammingError: 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sopds.authors.last_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

mysql-server=5.7.13-0ubuntu0.16.04.2

Лечится sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION

**Comment by mitshel** [comment]
Спасибо за информацию, однако новую версию сейчас потихоньку допиливаю в ветке v0.31-devel. Там совсем другой код, который использует Django ORM. Поэтому вероятно вашей ошибки уже не будет в этой версии.
