### ISSUE TITLE
django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')

### ISSUE THREAD

**Issue by ylapshin** [mitshel/sopds#17]
если воспользоваться инструкцией и использовать базу данных INNODB при выполнении пункта 1.4

**Comment by mitshel** [comment]
В инструкции - в разделе INNODB также написано следующее:
(На более старых версиях MySQL с ним возникают проблемы из-за ограничений на максимальную длину индексов.)
Таким образом, если у Вас современная версия MySQL (MariaDB>=10.2.2, Mysql>=5.7.9), то в настройках БД Mysql вместо указанных выше параметров OPTIONS просто используйте следующие...

Какая у вас версия MysqL ???

**Comment by ylapshin** [comment]
mysql  Ver 15.1 Distrib 10.1.19-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by mitshel** [comment]
Ну вот у Вас: 10.1.19-MariaDB. Минимальные требования для MariaDB: >=10.2.2

**Comment by ylapshin** [comment]
понял, прошу прощения
