### ISSUE TITLE
Если sopds в sub-uri сайта, то ссылка "Настройки" некорректная.

### ISSUE THREAD

**Issue by omgiafs** [mitshel/sopds#19]
Пример:

Сайт `http://example.com`
Sopds развернут в sub-uri `sopds`  (nginx + uWSGI), полный путь `http://example.com/sopds`.

При логине пользователя со статусом персонала ссылка на настройки в Header'е веб-страницы ведёт на `http://example.com/admin/` вместо `http://example.com/sopds/admin/`.

Надо править ссылку в файле [sopds_web_backend/templates/sopds_top.html#L21](https://github.com/mitshel/sopds/blob/master/sopds_web_backend/templates/sopds_top.html#L21)

**Comment by omgiafs** [comment]
После коммита прекрасно работает :) Спасибо!

**Comment by mitshel** [comment]
Исправлено
