### ISSUE TITLE
Сканирование по расписанию не работает

### ISSUE THREAD

**Issue by omgiafs** [mitshel/sopds#20]
Sopds на nginx + uWSGI.

manage.py:
`-rwxr--r-- 1 www-data www-data 248 Dec 14 11:11 manage.py`

sopds/settings.py:
```
USE_TZ = False
SOPDS_SCAN_SHED_MIN = '/5'
SOPDS_SCAN_SHED_HOUR = '*'
SOPDS_SCAN_SHED_DAY = '*'
SOPDS_SCAN_SHED_DOW = '*'
```

`systemctl uwsgi restart`,
страница в браузере обновлена.

Сканирования не происходит ни через 5, ни через 10 минут.

Или сканирование по расписанию из коробки не работает и надо где-то чего-то включить?
Можно, конечно, и кроном дёргать, но раз функционал заявлен в программе, то как добиться сканирования по расписанию?

Связка nginx + uWSGI ни при чем. Запускал сервер standalone, то же самое.
Менял параметры SOPDS_SCAN_SHED_XXX на простые, типа в 13 часов 12 минут - то же самое. Не сканирует в заданное время, независимо от таймзоны (выставлял 2 часовых параметра - местный и GMT).

**Comment by mitshel** [comment]
uwsgi не запускает сканирование. Для его работы нужно запустить отдельный воркер, можно в режиме демона.
В инструкции это описано:
python3 manage.py sopds_scanner start --daemon
