### ISSUE TITLE
Если sopds в sub-uri, то неверная ссылка на поиск в каталоге opds

### ISSUE THREAD

**Issue by omgiafs** [mitshel/sopds#21]
Пример:

Сайт `http://example.com`
Sopds развернут в sub-uri `sopds`  (nginx + uWSGI), полный путь `http://example.com/sopds`.
Путь к каталогу opds будет  `http://example.com/sopds/opds/`

При входе в каталог в отдаваемом xml ссылка на поиск имеет вид
`/opds/search/{searchTerms}/` вместо корректной
`/sopds/opds/search/{searchTerms}/` 

Править 
[opds_catalog/templates/opensearch.html#L6](https://github.com/mitshel/sopds/blob/master/opds_catalog/templates/opensearch.html#L6) и
[opds_catalog/feeds.py#L148](https://github.com/mitshel/sopds/blob/master/opds_catalog/feeds.py#L148)
Ну и в [opds_catalog/tests/test_feeds.py](https://github.com/mitshel/sopds/blob/master/opds_catalog/tests/test_feeds.py) при необходимости.

**Comment by mitshel** [comment]
исправил
