### ISSUE TITLE
Если sopds в sub-uri, то неверные ссылки на обложку книги и на удаление в модальном окне при удалении книги с книжной полки

### ISSUE THREAD

**Issue by omgiafs** [mitshel/sopds#22]
Продолжаем чистку хардкода :)

sopds в `example.com/sopds`.
На книжной полке и вообще везде правильная ссылка на картинку `/sopds/opds/cover/NUMBER/`, но в модальном окне книжной полки, появляющемся при подтверждении удаления книги с книжной полки, ссылка на обложку `/opds/cover/NUMBER/`.

Править [тут](https://github.com/mitshel/sopds/blob/c4f8e2789df27193505cbd5feaf7a3f4569f29fc/sopds_web_backend/templates/sopds_books.html#L7-L8).

Что-то мне подсказывает, что в коде надо править все ссылки, начинающиеся с `/`...

**Comment by mitshel** [comment]
Все правильно вам что-то подсказывает. Однако к сожалению пока не могу достаточно времени уделить проекту. Поэтому спасибо за участие. По issue #22 исправлю в ближайшее время

**Comment by mitshel** [comment]
fixed.
