### ISSUE TITLE
Страницам нужен нормальный title

### ISSUE THREAD

**Issue by omgiafs** [mitshel/sopds#25]
Сейчас title у страниц выглядит как, хм, на отладочной версии:
'http://www.example.com/sopds/web/search/books/&searchtype=i&searchterms=4567454'

В коде веб-страницы тег 'title' пустой, браузер что хочет, то и ставит.

**Comment by mitshel** [comment]
Будет исправлено в версии 0.41. (Сейчас в ветке v0.41-devel)
