### ISSUE TITLE
Лог авторизации

### ISSUE THREAD

**Issue by ptah-alexs** [mitshel/sopds#30]
Добавьте пожалуйста лог неудачных попыток авторизации, что бы можно было скармливать его fail2ban'у.

**Comment by mitshel** [comment]
Сделал в ветке v0.44-devel
при неудаче авторизации в OPDS в логе HTTP ошибка 401
при неудаче авторизации в WEB в логе HTTP ошибка 403

**Comment by ptah-alexs** [comment]
Спасибо.

**Comment by ptah-alexs** [comment]
Можно добавить в лог еще IP с которого идёт попытка авторизации? И главное можно также в лог писать события с wsgi версии?
