### ISSUE TITLE
[feature request]Сортировка в серии

### ISSUE THREAD

**Issue by ptah-alexs** [mitshel/sopds#31]
Сейчас при показе книг в серии они отсортированы по алфавиту. Возможно стоит их показывать согласно номеру в серии. Хотя бы в качестве опции. Заранее спасибо.

**Comment by ptah-alexs** [comment]
Или можно просто показывать номер в серии в информации о книге.

**Comment by mitshel** [comment]
Изменения внесены в версию 0.44-devel
