### ISSUE TITLE
Can't download books via wsgi version

### ISSUE THREAD

**Issue by ptah-alexs** [mitshel/sopds#32]
I'd tried in 0.43 and 0.44-dev versions

log for 0.43: [link](https://ptah-alexs.info/owncloud/index.php/s/FxwdjBbijAQ9g9k)

**Comment by mitshel** [comment]
Проверил, все работает. Проверьие права на фалы. Необходимо чтобы web-сервер имел доступ к файлм книг.

**Comment by ptah-alexs** [comment]
Спасибо, помогло. Про это я что-то не подумал.
