### ISSUE TITLE
Некорректное сканирование inpx

### ISSUE THREAD

**Issue by nidjan** [mitshel/sopds#37]
В коде формат inp-файлов inpx-каталого жёстко задан, а ведь он может задаваться в structure.info, лежащем в inpx-каталоге. Раз.
Два. Книги могут (внезапно) лежать не в inp-файлах-архивах внутри каталога, а в сторонней директории (zip), которая указывается в соответствующей строке inp-файла. Два.

Счас я попробую это сделать. Изменить inpx_parser.py

**Comment by mitshel** [comment]
Согласен с Вами. Реализация получения данных из INPX несколько не полная. Спасибо за помощь проекту.

**Comment by nidjan** [comment]
Теперь inpx_парсер читает прописанную структуру inp, если есть файл описания.
А в sopdscan я переделал inpx_callback так, чтобы он вносил в путь к книге не inp-файл, а архив с книгой, указанный в inp. Именно переделал, поскольку написать нормальную развилку у меня не получилось.

**Comment by mitshel** [comment]
Pull request сделайте

**Comment by nidjan** [comment]
Блин, чувствую себя ламером. Не смог. Вот эти два отредактированные файла.

[opds_catalog.zip](https://github.com/mitshel/sopds/files/1957756/opds_catalog.zip)

**Comment by mitshel** [comment]
Хотел внести ваши изменения в проект, Cо structure.info все ясно. Но вот с обработка archives.info у меня вызывает сомнения, в первую очередь из-за того, что не могу найти описание этого файла. И даже уже полного описания формата INPX найти тоже не удается.
Киньте пожалуйста ссылку на описания этих структур, если у вас есть. Ну или ссылку на пример INPX со включенными structure.info и archives.info.
К сожалению я не особо пользуюсь INPX форматом, но думаю у людей есть интерес подключать такие библиотеки, поэтому хотел бы исправить указанную вами недоработку.

**Comment by Lekos555** [comment]
Дмитрий, здравствуйте.
Я, конечно, тезка и SOPDS использую и слежу за развитием, но данный запрос подавал не я :)
И сам не пользуюсь INPX. :)



>Суббота,  7 июля 2018, 21:01 +03:00 от Shelepnev Dmitry <notifications@github.com>:
>
>Хотел внести ваши изменения в проект, Cо structure.info все ясно. Но вот с обработка archives.info у меня вызывает сомнения, в первую очередь из-за того, что не могу найти описание этого файла. И даже уже полного описания формата INPX найти тоже не удается.
>Киньте пожалуйста ссылку на описания этих структур, если у вас есть. Ну или ссылку на пример INPX со включенными structure.info и archives.info.
>К сожалению я не особо пользуюсь INPX форматом, но думаю у людей есть интерес подключать такие библиотеки, поэтому хотел бы исправить указанную вами недоработку.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Dmitriy Menushin

**Comment by nidjan** [comment]
Ещё, кстати, коллеги
https://github.com/rupor-github/InpxCreator

**Comment by nidjan** [comment]
Ой.
Восстанавливаю.
Откуда я брал данные по формату structure:
https://forum.myhomelib.org/viewtopic.php?f=17&t=16
Коллеги с другой стороны:
https://github.com/rupor-github/InpxCreator
Archives.info - это построчный список просканированных архивов каталога - путь к файлу от местонахождения inpx, если в одной папке - то просто имя, в конце строки - CR
Пример 
https://yadi.sk/d/xIIVWS0i3YyCdL

Пример -
