### ISSUE TITLE
Добавление описания настройки Apache в README(_RUS)

### ISSUE THREAD

**Issue by xatage** [mitshel/sopds#41]
Было бы здорово добавить в README описание запуска SOPDS с помощью Apache веб сервера (в т.ч. с использованием имеющихся SSL сертификатов). Как например существующие инструкции по использованию разных БД.

Ну или если это выходит за рамки проекта, буду очень признателен, если кто-нибудь сможет написать мне инструкцию для выше описанного вопроса.

**Comment by mitshel** [comment]
Поищите пожалуйста на форуме [http://www.sopds.ru/index.php/forum/index](http://www.sopds.ru/index.php/forum/index)
Там вроде бы  есть необходимая Вам информация.
