### ISSUE TITLE
Проблемы с шаблоном

### ISSUE THREAD

**Issue by HalfWorm** [mitshel/sopds#46]
После установкт версии 0.47 на страничке http://xxxxxxxxx:8001/admin/constance/config/
проблемы с шаблоном.

TemplateDoesNotExist at /admin/constance/config/
admin/constance/includes/../../../../venv/Lib/site-packages/constance/templates/admin/constance/includes/results_list.html

**Comment by HalfWorm** [comment]
Моих знаний питона недостаточно но несмотря на запись DJANGO='django>=2.0,<2.2' у меня идет установка версии 2.2

**Comment by mitshel** [comment]
Спасибо...
Попробуйте v0.48-devel

**Comment by HalfWorm** [comment]
Ок. Работает.

В правом нижнем углу ошибка в номере версии. 'SOPDS.RU v.0.47-deve' при v0.48
