### ISSUE TITLE
Ошибка скачивания в FBReader

### ISSUE THREAD

**Issue by WarL0ckNet** [mitshel/sopds#67]
При попытке скачивания книги из OPDS в FBReader под андроид выдает 404 ошибку.
В логах 
GET /opds/convert/3156/epub/ HTTP/1.1" 404 866 "-" "FBReader/3.0.29 (Android 8.1.0, vince, Redmi 5 Plus)
Сама книга в fb2, зачем пытаться конвертировать в epub?

**Comment by mitshel** [comment]
Ну так отключите конвертацию, установив в настройках  SOPDS_FB2TOEPUB = "" и SOPDS_FB2TOMOBI = ""

**Comment by WarL0ckNet** [comment]
Жаль, хотелось бы оставить возможность скачивать с веб в других форматах
